const prompt = require("prompt-sync")()
const funcionario = prompt("Funcionário: ")
const salario = Number(prompt("Salário Mensal R$: "))
const tempo = Number(prompt("Tempo de Serviço (Anos): "))
const quadrientos = Math.floor(tempo / 4)
const acrecimo = Number(salario * ((Math.pow((1+0.01), quadrientos))) - salario)
console.log(`Funcionário: ${funcionario}`)
console.log(`Quadriênios: ${quadrientos}`)
console.log(`Salário Final R$: ${(salario+acrecimo).toFixed(2).replace(/\./g, ",")}`)